---
title: "Create EML"
output: html_document
---

## The `make_eml` function

The information rich and machine readable EML metadata file should contain all the necessary content, in the correct format, and in the right schema locations according with best practices informed by scientists who use this information and data repositories who serve it in a human discoverable and readable form. In addition to performing all these tasks, the `make_eml` function adds another layer of auto-extracted metadata to the EML based on template contents and data object types. Usage of `make_eml` differs slightly based on data package contents comprised of:

* **Data tables** Only contains data tables
* **Other entities** Only contains non-table data types and other digital objects
* **Data tables and other entities** Contains both data tables and other entities

Below are examples of using `make_eml` to create EML for each of these use cases.

## Make EML for data tables

The most common type of data package only contains data tables. To create EML for this package type, the core metadata and table attribute templates should be complete, as well as the categorical variables and custom units templates if necessary. Some additional metadata information is supplied in function arguments including:

*  **path**  Path to template files
*  **data.path** Path to data files
*  ** eml.path** Path to where the EML file will be written
*  **dataset.title** Title of the data package
*  **temporal.coverage** Beginning and ending dates of the data using the format YYYY-MM-DD
*  **geographic.coordinates** (required if not using the _geographic_coverage.txt_ template) A vector of decimal degree coordinates in the order: north, east, south, west, where latitudes south of the equator and longitudes west of the prime meridian are negative.
*  **maintenance.description** Indicator of whether data collection is ‘ongoing’ or ‘completed’
*  **data.table** Data table file names.
*  **data.table.description** Data table descriptions listed in the same order as under `data.table`
*  **data.table.quote.character** (required if data tables contain quote characters) Quote characters used in each data table in the same order as under `data.table`. Use “\”” for quotes and “\’” for apostrophes.
*  **data.url** (required if uploading data to a repository via URL) A publicly accessible URL to the data
*  **user.id** (optional) ID(s) of data repository user account(s) to which the data package will be uploaded.
*  **user.domain** (optional) Domain of the `user.id`(s).
*  **package.id** (optional) Data package identifier in the format expected by the receiving data repository.

EXAMPLE

## Make EML for other entities

Some data packages only contain non-tabular data (e.g. geospatial vector, NetCDF, images) or other digital objects (e.g. processing and analysis scripts, modeling code, .pdf). To create EML for this package type, the core metadata templates need to be completed. Several of the same file type, or related file types, should be grouped into an archive format (e.g. zip, rar, tar). Some additional metadata information is supplied in function arguments including:

*  **path**  Path to template files
*  **data.path** Path to data files and other digital objects
*  ** eml.path** Path to where the EML file will be written
*  **dataset.title** Title of the data package
*  **temporal.coverage** Beginning and ending dates of the data using the format YYYY-MM-DD
*  **geographic.coordinates** (required if not using the _geographic_coverage.txt_ template) A vector of decimal degree coordinates in the order: north, east, south, west, where latitudes south of the equator and longitudes west of the prime meridian are negative.
*  **maintenance.description** Indicator of whether data collection is ‘ongoing’ or ‘completed’
*  **other.entity** File names of non-tabular data and/or other digital objects
*  **other.entity.description** Other entity descriptions listed in the same order as under `other.entity`
*  **data.url** (required if uploading data and/or objects to a repository via URL) A publicly accessible URL to the data
*  **user.id** (optional) ID(s) of data repository user account(s) to which the data package will be uploaded.
*  **user.domain** (optional) Domain of the `user.id`(s).
*  **package.id** (optional) Data package identifier in the format expected by the receiving data repository.

EXAMPLE

## Make EML for data tables and other entities

A third type of data package contains both data tables and other entities. To create EML for this package type, the core metadata and table attribute templates should be complete, as well as the categorical variables and custom units templates if necessary. Some additional metadata information is supplied in function arguments including:

*  **path**  Path to template files
*  **data.path** Path to data files
*  ** eml.path** Path to where the EML file will be written
*  **dataset.title** Title of the data package
*  **temporal.coverage** Beginning and ending dates of the data using the format YYYY-MM-DD
*  **geographic.coordinates** (required if not using the _geographic_coverage.txt_ template) A vector of decimal degree coordinates in the order: north, east, south, west, where latitudes south of the equator and longitudes west of the prime meridian are negative.
*  **maintenance.description** Indicator of whether data collection is ‘ongoing’ or ‘completed’
*  **data.table** Data table file names.
*  **data.table.description** Data table descriptions listed in the same order as under `data.table`
*  **data.table.quote.character** (required if data tables contain quote characters) Quote characters used in each data table in the same order as under `data.table`. Use “\”” for quotes and “\’” for apostrophes.
*  **other.entity** File names of non-tabular data and/or other digital objects
*  **other.entity.description** Other entity descriptions listed in the same order as under `other.entity`
*  **data.url** (required if uploading data to a repository via URL) A publicly accessible URL to the data
*  **user.id** (optional) ID(s) of data repository user account(s) to which the data package will be uploaded.
*  **user.domain** (optional) Domain of the `user.id`(s).
*  **package.id** (optional) Data package identifier in the format expected by the receiving data repository.

EXAMPLE
