---
title: "EML assembly (an example)"
author: "Colin Smith"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{example}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

Assembly line overview. See introduction vignette.

## Installation
Not in formal repo YET. Use devtools to install from github.

Figure

## Build the parts:

### Setup work space

### Import data

### Import templates

### Complete templates

## Fabricate addtional parts:

### Define factors

### Extract geographic information

## Assemble the parts:

### Call on the assembler
### Compile attributes





While at first this may seem daunting. Of course this is a new process. Really, you have already done the most challengin part. Collected and refined the data to a usable set. You have all the information, now log it through these steps. Give your self a couple days to work through all this.

## Current capabilities and requirements
Data tables, comma or tab delimited

Our priorities for building up the assembly line to produce EML for: spatial vectors and spatial raster
data.

## Collaboration
[Collaborate with us](https://github.com/EDIorg/emlAssemblyLine)


## References
[Ecological Metadata Language](https://knb.ecoinformatics.org/#external//emlparser/docs/index.html)

[EML R code package](https://github.com/ropensci/EML)

# Assembling EML for an example dataset.





## Figures

The figure sizes have been customised so that you can easily put two images side-by-side. 

```{r, fig.show='hold'}
plot(1:10)
plot(10:1)
```

You can enable figure captions by `fig_caption: yes` in YAML:

    output:
      rmarkdown::html_vignette:
        fig_caption: yes

Then you can use the chunk option `fig.cap = "Your figure caption."` in **knitr**.

